name: wit_by_bit
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura_book.otf
          weight: 200
        - asset: assets/fonts/futura_heavy.otf
          weight: 700
        - asset: assets/fonts/futura_medium.otf
          weight: 400
    